[package]
name = "vtex"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
futures = "0.3.19"
log = "0.4.14"
reqwest = { version = "0.11.7", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.59"
tokio = { version = "1", features = ["full"] }